//
//  DSYPlaylistButton.m
//  MiniPlayer
//
//  Created by Syed Haris Ali on 3/5/14.
//  Copyright (c) 2014 Beats Music. All rights reserved.
//

#import "DSYPlaylistButton.h"

@implementation DSYPlaylistButton

-(void)drawCustomIcon
{
    //// Frames
    NSRect bounds = self.bounds;
    
    //// playlistIcon Drawing
    NSBezierPath* playlistIconPath = [NSBezierPath bezierPath];
    [playlistIconPath moveToPoint: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.44836 * NSWidth(bounds), NSMinY(bounds) + 0.44643 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.47026 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.47814 * NSWidth(bounds), NSMinY(bounds) + 0.44643 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.39437 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.41859 * NSWidth(bounds), NSMinY(bounds) + 0.44643 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.39437 * NSWidth(bounds), NSMinY(bounds) + 0.47026 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.44836 * NSWidth(bounds), NSMinY(bounds) + 0.55275 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.39437 * NSWidth(bounds), NSMinY(bounds) + 0.52891 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.41859 * NSWidth(bounds), NSMinY(bounds) + 0.55275 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.47814 * NSWidth(bounds), NSMinY(bounds) + 0.55275 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.52891 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.52891 * NSHeight(bounds))];
    [playlistIconPath lineToPoint: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds))];
    [playlistIconPath lineToPoint: NSMakePoint(NSMinX(bounds) + 0.50236 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds))];
    [playlistIconPath closePath];
    [playlistIconPath moveToPoint: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.44836 * NSWidth(bounds), NSMinY(bounds) + 0.48186 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.48982 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.43845 * NSWidth(bounds), NSMinY(bounds) + 0.48186 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.46636 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.45829 * NSWidth(bounds), NSMinY(bounds) + 0.48186 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.46636 * NSWidth(bounds), NSMinY(bounds) + 0.48982 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.44836 * NSWidth(bounds), NSMinY(bounds) + 0.51732 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.46636 * NSWidth(bounds), NSMinY(bounds) + 0.50935 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.45829 * NSWidth(bounds), NSMinY(bounds) + 0.51732 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.43845 * NSWidth(bounds), NSMinY(bounds) + 0.51732 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.50935 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.50935 * NSHeight(bounds))];
    [playlistIconPath lineToPoint: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds))];
    [playlistIconPath lineToPoint: NSMakePoint(NSMinX(bounds) + 0.43037 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds))];
    [playlistIconPath closePath];
    [playlistIconPath moveToPoint: NSMakePoint(NSMinX(bounds) + 0.54915 * NSWidth(bounds), NSMinY(bounds) + 0.34363 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.49908 * NSWidth(bounds), NSMinY(bounds) + 0.35188 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.53211 * NSWidth(bounds), NSMinY(bounds) + 0.34363 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.51533 * NSWidth(bounds), NSMinY(bounds) + 0.34652 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.44836 * NSWidth(bounds), NSMinY(bounds) + 0.34363 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.48314 * NSWidth(bounds), NSMinY(bounds) + 0.34656 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.46609 * NSWidth(bounds), NSMinY(bounds) + 0.34363 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.28998 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.36103 * NSWidth(bounds), NSMinY(bounds) + 0.34363 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.28998 * NSWidth(bounds), NSMinY(bounds) + 0.41359 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.44836 * NSWidth(bounds), NSMinY(bounds) + 0.65554 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.28998 * NSWidth(bounds), NSMinY(bounds) + 0.58559 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.36103 * NSWidth(bounds), NSMinY(bounds) + 0.65554 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.49908 * NSWidth(bounds), NSMinY(bounds) + 0.64730 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.46609 * NSWidth(bounds), NSMinY(bounds) + 0.65554 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.48314 * NSWidth(bounds), NSMinY(bounds) + 0.65262 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.54915 * NSWidth(bounds), NSMinY(bounds) + 0.65554 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.51533 * NSWidth(bounds), NSMinY(bounds) + 0.65266 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.53211 * NSWidth(bounds), NSMinY(bounds) + 0.65554 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.70753 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.63648 * NSWidth(bounds), NSMinY(bounds) + 0.65554 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.70753 * NSWidth(bounds), NSMinY(bounds) + 0.58559 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.54915 * NSWidth(bounds), NSMinY(bounds) + 0.34363 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.70753 * NSWidth(bounds), NSMinY(bounds) + 0.41359 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.63648 * NSWidth(bounds), NSMinY(bounds) + 0.34363 * NSHeight(bounds))];
    [playlistIconPath closePath];
    [playlistIconPath moveToPoint: NSMakePoint(NSMinX(bounds) + 0.33319 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.44836 * NSWidth(bounds), NSMinY(bounds) + 0.38618 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.33319 * NSWidth(bounds), NSMinY(bounds) + 0.43704 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.38485 * NSWidth(bounds), NSMinY(bounds) + 0.38618 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.49095 * NSWidth(bounds), NSMinY(bounds) + 0.39430 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.46340 * NSWidth(bounds), NSMinY(bounds) + 0.38618 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.47776 * NSWidth(bounds), NSMinY(bounds) + 0.38910 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.49710 * NSWidth(bounds), NSMinY(bounds) + 0.39698 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.49305 * NSWidth(bounds), NSMinY(bounds) + 0.39511 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.49507 * NSWidth(bounds), NSMinY(bounds) + 0.39604 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.50035 * NSWidth(bounds), NSMinY(bounds) + 0.39850 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.49818 * NSWidth(bounds), NSMinY(bounds) + 0.39747 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.49929 * NSWidth(bounds), NSMinY(bounds) + 0.39797 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.50520 * NSWidth(bounds), NSMinY(bounds) + 0.40106 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.50198 * NSWidth(bounds), NSMinY(bounds) + 0.39933 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.50361 * NSWidth(bounds), NSMinY(bounds) + 0.40017 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.51070 * NSWidth(bounds), NSMinY(bounds) + 0.40435 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.50705 * NSWidth(bounds), NSMinY(bounds) + 0.40212 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.50889 * NSWidth(bounds), NSMinY(bounds) + 0.40321 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.51317 * NSWidth(bounds), NSMinY(bounds) + 0.40589 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.51152 * NSWidth(bounds), NSMinY(bounds) + 0.40488 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.51237 * NSWidth(bounds), NSMinY(bounds) + 0.40537 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56102 * NSWidth(bounds), NSMinY(bounds) + 0.47605 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.53725 * NSWidth(bounds), NSMinY(bounds) + 0.42210 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.55476 * NSWidth(bounds), NSMinY(bounds) + 0.44703 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56141 * NSWidth(bounds), NSMinY(bounds) + 0.47806 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.56116 * NSWidth(bounds), NSMinY(bounds) + 0.47672 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.56129 * NSWidth(bounds), NSMinY(bounds) + 0.47739 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56269 * NSWidth(bounds), NSMinY(bounds) + 0.48635 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.56194 * NSWidth(bounds), NSMinY(bounds) + 0.48078 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.56237 * NSWidth(bounds), NSMinY(bounds) + 0.48355 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56300 * NSWidth(bounds), NSMinY(bounds) + 0.48907 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.56279 * NSWidth(bounds), NSMinY(bounds) + 0.48724 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.56292 * NSWidth(bounds), NSMinY(bounds) + 0.48815 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56355 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.56332 * NSWidth(bounds), NSMinY(bounds) + 0.49254 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.56355 * NSWidth(bounds), NSMinY(bounds) + 0.49603 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56300 * NSWidth(bounds), NSMinY(bounds) + 0.51011 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.56355 * NSWidth(bounds), NSMinY(bounds) + 0.50314 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.56332 * NSWidth(bounds), NSMinY(bounds) + 0.50663 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56269 * NSWidth(bounds), NSMinY(bounds) + 0.51285 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.56292 * NSWidth(bounds), NSMinY(bounds) + 0.51102 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.56279 * NSWidth(bounds), NSMinY(bounds) + 0.51193 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56141 * NSWidth(bounds), NSMinY(bounds) + 0.52111 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.56237 * NSWidth(bounds), NSMinY(bounds) + 0.51563 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.56194 * NSWidth(bounds), NSMinY(bounds) + 0.51839 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.56102 * NSWidth(bounds), NSMinY(bounds) + 0.52312 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.56129 * NSWidth(bounds), NSMinY(bounds) + 0.52178 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.56116 * NSWidth(bounds), NSMinY(bounds) + 0.52247 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.51317 * NSWidth(bounds), NSMinY(bounds) + 0.59328 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.55476 * NSWidth(bounds), NSMinY(bounds) + 0.55214 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.53725 * NSWidth(bounds), NSMinY(bounds) + 0.57708 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.51070 * NSWidth(bounds), NSMinY(bounds) + 0.59482 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.51237 * NSWidth(bounds), NSMinY(bounds) + 0.59381 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.51152 * NSWidth(bounds), NSMinY(bounds) + 0.59430 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.50520 * NSWidth(bounds), NSMinY(bounds) + 0.59811 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.50889 * NSWidth(bounds), NSMinY(bounds) + 0.59596 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.50705 * NSWidth(bounds), NSMinY(bounds) + 0.59708 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.50035 * NSWidth(bounds), NSMinY(bounds) + 0.60067 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.50361 * NSWidth(bounds), NSMinY(bounds) + 0.59901 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.50198 * NSWidth(bounds), NSMinY(bounds) + 0.59984 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.49710 * NSWidth(bounds), NSMinY(bounds) + 0.60222 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.49929 * NSWidth(bounds), NSMinY(bounds) + 0.60120 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.49818 * NSWidth(bounds), NSMinY(bounds) + 0.60171 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.49095 * NSWidth(bounds), NSMinY(bounds) + 0.60488 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.49507 * NSWidth(bounds), NSMinY(bounds) + 0.60313 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.49305 * NSWidth(bounds), NSMinY(bounds) + 0.60406 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.44836 * NSWidth(bounds), NSMinY(bounds) + 0.61302 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.47776 * NSWidth(bounds), NSMinY(bounds) + 0.61007 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.46340 * NSWidth(bounds), NSMinY(bounds) + 0.61302 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.33319 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.38485 * NSWidth(bounds), NSMinY(bounds) + 0.61302 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.33319 * NSWidth(bounds), NSMinY(bounds) + 0.56213 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.33319 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.33319 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.33319 * NSWidth(bounds), NSMinY(bounds) + 0.56213 * NSHeight(bounds))];
    [playlistIconPath closePath];
    [playlistIconPath moveToPoint: NSMakePoint(NSMinX(bounds) + 0.55747 * NSWidth(bounds), NSMinY(bounds) + 0.61271 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.60591 * NSWidth(bounds), NSMinY(bounds) + 0.51551 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.58465 * NSWidth(bounds), NSMinY(bounds) + 0.58743 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.60206 * NSWidth(bounds), NSMinY(bounds) + 0.55320 * NSHeight(bounds))];
    [playlistIconPath lineToPoint: NSMakePoint(NSMinX(bounds) + 0.60591 * NSWidth(bounds), NSMinY(bounds) + 0.51545 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.60653 * NSWidth(bounds), NSMinY(bounds) + 0.50765 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.60620 * NSWidth(bounds), NSMinY(bounds) + 0.51287 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.60640 * NSWidth(bounds), NSMinY(bounds) + 0.51027 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.60675 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.60667 * NSWidth(bounds), NSMinY(bounds) + 0.50497 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.60675 * NSWidth(bounds), NSMinY(bounds) + 0.50229 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.60653 * NSWidth(bounds), NSMinY(bounds) + 0.49153 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.60675 * NSWidth(bounds), NSMinY(bounds) + 0.49689 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.60667 * NSWidth(bounds), NSMinY(bounds) + 0.49421 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.60591 * NSWidth(bounds), NSMinY(bounds) + 0.48373 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.60640 * NSWidth(bounds), NSMinY(bounds) + 0.48891 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.60620 * NSWidth(bounds), NSMinY(bounds) + 0.48633 * NSHeight(bounds))];
    [playlistIconPath lineToPoint: NSMakePoint(NSMinX(bounds) + 0.60591 * NSWidth(bounds), NSMinY(bounds) + 0.48367 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.55747 * NSWidth(bounds), NSMinY(bounds) + 0.38646 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.60206 * NSWidth(bounds), NSMinY(bounds) + 0.44598 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.58465 * NSWidth(bounds), NSMinY(bounds) + 0.41174 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.66432 * NSWidth(bounds), NSMinY(bounds) + 0.49959 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.61711 * NSWidth(bounds), NSMinY(bounds) + 0.39066 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.66432 * NSWidth(bounds), NSMinY(bounds) + 0.43981 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.55747 * NSWidth(bounds), NSMinY(bounds) + 0.61271 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.66432 * NSWidth(bounds), NSMinY(bounds) + 0.55937 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.61711 * NSWidth(bounds), NSMinY(bounds) + 0.60851 * NSHeight(bounds))];
    [playlistIconPath curveToPoint: NSMakePoint(NSMinX(bounds) + 0.55747 * NSWidth(bounds), NSMinY(bounds) + 0.61271 * NSHeight(bounds)) controlPoint1: NSMakePoint(NSMinX(bounds) + 0.55747 * NSWidth(bounds), NSMinY(bounds) + 0.61271 * NSHeight(bounds)) controlPoint2: NSMakePoint(NSMinX(bounds) + 0.61711 * NSWidth(bounds), NSMinY(bounds) + 0.60851 * NSHeight(bounds))];
    [playlistIconPath closePath];
    [playlistIconPath setMiterLimit: 4];
    [playlistIconPath setWindingRule: NSEvenOddWindingRule];
    [self.iconFillColor setFill];
    [playlistIconPath fill];
}

@end
