#import "_DSYUser.h"

/**
 The DSYUser, a subclass of the _DSYUser (a private NSManagedObject subclass generated by Mogenerator using the Model.xcdatamodeld - See the 'Run Mogenerator' target), provides a Core Data class that represents a user from the Beats Music API. This class contains class methods to directly import the JSON parsed NSDictionary and NSArray representations of a user directly from the API.
 */
@interface DSYUser : _DSYUser {}

#pragma mark - Class Initializer
///-----------------------------------------------------------
/// @name Class Initializer
///-----------------------------------------------------------

/**
 Creates a DSYUser using an NSDictionary representation of the user. Will try to parse the dictionary for keys = user_context. This method will first load the DSYUser if it already exists in the Core Data store and will only update the key-value information if a local user with the same id is present.
 @param dictionary An NSDictionary with the following keys: keys = user_context.
 @return A DSYUser created using the input NSDictionary.
 */
+(DSYUser *)userFromTokenDictionary:(NSDictionary *)tokenDictionary;

#pragma mark - Setting / Getting Session User
///-----------------------------------------------------------
/// @name Setting / Getting Session User
///-----------------------------------------------------------

/**
 Sets the shared session user (the logged in user) for the application to use.
 @param sessionUser A DSYUser representing the shared session user (i.e. the logged in user)
 */
+(void)setSessionUser:(DSYUser *)sessionUser;

/**
 Provides the shared session user (the logged in user) the application is currently using.
 @return A DSYUser instance representing the shared session user. Will be nil if a session user was not set.
 */
+(DSYUser *)sessionUser;

@end
